version: '3.3'

services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - skillab-network
    labels:
      io.portainer.accesscontrol.teams: skillab-all

networks:
  skillab-network:
    external: true
