version: '3.3'

services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    networks:
      - skillab-network
    labels:
      io.portainer.accesscontrol.teams: skillab-all

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - skillab-network
    labels:
      io.portainer.accesscontrol.teams: skillab-all

networks:
  skillab-network:
    external: true
