version: "3.3"

services:
  # -- UI --
  ui:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: ui
    environment:
      - REACT_APP_API_URL_KU=https://portal.skillab-project.eu/ku-detection
      - REACT_APP_API_URL_KPI=https://portal.skillab-project.eu/policy
      - REACT_APP_API_URL_JBPM=https://portal.skillab-project.eu/jbpm/business-central/kie-wb.jsp
      - REACT_APP_API_URL_TRACKER=http://skillab-tracker.csd.auth.gr
      - REACT_APP_API_URL_LABOUR_DEMAND=https://portal.skillab-project.eu/labor-market-demand
      - REACT_APP_API_URL_SKILLS_REQUIRED=https://portal.skillab-project.eu/required-skills
      - REACT_APP_API_URL_SKILLS_DIVERSITY=https://portal.skillab-project.eu/diversity-analysis
      # - REACT_APP_API_URL_SKILL_ARCHETYPAL_DIVERSITY=http://localhost:8087
      - REACT_APP_API_URL_SKILL_DEMAND_MATRIX=https://portal.skillab-project.eu/hcv
    ports:
      - '3000:3000'
    restart: unless-stopped


  # -- User management --
  user-management-backend:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: user-management-backend
    depends_on:
      - user-management-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-management-db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    ports:
      - '8086:8080'

  user-management-db:
    image: postgres:14.7
    container_name: user-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    restart: unless-stopped
    volumes:
       - user_management_postgresql_data:/var/lib/postgresql/data


  # -- KPI Management --
  backend-policy:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: backend-policy
    depends_on:
      - db-policy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-policy:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=30a301d7257
    ports:
      - '8085:8080'
    restart: unless-stopped

  db-policy:
    image: postgres:14.7
    container_name: db-policy
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 30a301d7257
      POSTGRES_DB: test_db
    volumes:
       - policy_postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped


  # -- JBPM --
  jbpm-policy:
    image: nikosnikolaidis/jbpm-allowframes:7.61.0.Final
    container_name: jbpm-policy
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: jbpm-postgres-policy
    depends_on:
      - jbpm-postgres-policy
    volumes:
      - niogit:/opt/jboss/wildfly/.niogit:Z
    ports:
      - '8181:8080'
      - '8001:8001'
  
  jbpm-postgres-policy:
    image: postgres:14.7
    container_name: jbpm-postgres-policy
    volumes:
      - policy_postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
    restart: unless-stopped


  # -- Analysis Diversity --
  analysis-diversity:
    container_name: analysis-diversity
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    environment:
      - URL=https://skillab-tracker.csd.auth.gr/api
    ports:
      - "8870:8870"
    restart: unless-stopped
  
  
  # -- to Add more --
  # curiculum (for general analysis data)? & archetypal & hcv
  # and forecasters
  
  
volumes:
  user_management_postgresql_data:
  policy_postgresql_data:
  niogit:
  policy_postgres_db: