version: "3.3"

services:
  # -- UI --
  ui:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: ui
    environment:
      - REACT_APP_API_URL_KU=https://portal.skillab-project.eu/ku-detection
      - REACT_APP_API_URL_KPI=https://portal.skillab-project.eu/policy
      - REACT_APP_API_URL_JBPM=https://portal.skillab-project.eu/jbpm/business-central/kie-wb.jsp
      - REACT_APP_API_URL_TRACKER=http://skillab-tracker.csd.auth.gr
      - REACT_APP_API_URL_LABOUR_DEMAND=https://portal.skillab-project.eu/labor-market-demand
      - REACT_APP_API_URL_SKILLS_REQUIRED=https://portal.skillab-project.eu/required-skills
      - REACT_APP_API_URL_SKILLS_DIVERSITY=https://portal.skillab-project.eu/diversity-analysis
      # - REACT_APP_API_URL_SKILL_ARCHETYPAL_DIVERSITY=http://localhost:8087
      - REACT_APP_API_URL_SKILL_DEMAND_MATRIX=https://portal.skillab-project.eu/hcv
    ports:
      - '3000:3000'
    restart: unless-stopped


  # -- User management --
  user-management-backend:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: user-management-backend
    depends_on:
      - user-management-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-management-db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - '8086:8080'

  user-management-db:
    image: postgres:14.7
    container_name: user-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
       - user_management_postgresql_data:/var/lib/postgresql/data


  # -- Skillab analysis --
  skillab-analysis:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: skillab-analysis
    ports:
      - "8873:8872"
    restart: unless-stopped
  

  # -- KU Detection --
  ku-detection-backend:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: ku-detection-backend
    depends_on:
      - ku-detection-db
    environment:
      - DB_HOST=ku-detection-db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - '5000:5000'
    restart: unless-stopped

  ku-detection-db:
    image: postgres:16.2
    container_name: ku-detection-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - ku_detection_postgresql:/var/lib/postgresql
      - ku_detection_postgresql_data:/var/lib/postgresql/data
    ports:
      - '5430:5432'
    restart: unless-stopped
  
  
  # --  --
  # -- to Add more --

  
volumes:
  user_management_postgresql_data:
  ku_detection_postgresql:
  ku_detection_postgresql_data: