version: "3.3"

services:
  # -- UI --
  ui:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: ui
    environment:
      - REACT_APP_API_URL_KU=https://portal.skillab-project.eu/ku-detection
      - REACT_APP_API_URL_KPI=https://portal.skillab-project.eu/policy
      - REACT_APP_API_URL_JBPM=https://portal.skillab-project.eu/jbpm/business-central/kie-wb.jsp
      - REACT_APP_API_URL_TRACKER=http://skillab-tracker.csd.auth.gr
      - REACT_APP_API_URL_LABOUR_DEMAND=https://portal.skillab-project.eu/labor-market-demand
      - REACT_APP_API_URL_SKILLS_REQUIRED=https://portal.skillab-project.eu/required-skills
      - REACT_APP_API_URL_SKILLS_DIVERSITY=https://portal.skillab-project.eu/diversity-analysis
      # - REACT_APP_API_URL_SKILL_ARCHETYPAL_DIVERSITY=http://localhost:8087
      - REACT_APP_API_URL_SKILL_DEMAND_MATRIX=https://portal.skillab-project.eu/hcv
    ports:
      - '3000:3000'
    restart: unless-stopped


  # -- User management --
  user-management-backend:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: user-management-backend
    depends_on:
      - user-management-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-management-db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    ports:
      - '8086:8080'

  user-management-db:
    image: postgres:14.7
    container_name: user-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    restart: unless-stopped
    volumes:
       - user_management_postgresql_data:/var/lib/postgresql/data


  # -- Analysis Diversity --
  analysis-diversity:
    container_name: analysis-diversity
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    environment:
      - URL=https://skillab-tracker.csd.auth.gr/api
    ports:
      - "8870:8870"
    restart: unless-stopped


  # -- Curiculum --
  curriculum-skill-mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    container_name: curriculum-skill-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillcrawl
    volumes:
      - curriculum_skills_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  curriculum-skill-service:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: curriculum-skills
    depends_on:
      curriculum-skill-mysql:
        condition: service_healthy
    ports:
      - "5002:8000"
    volumes:
      - ./curriculum:/app/curriculum
      - ./crawler_json:/app/crawler_json
      - ./world_universities_and_domains.json:/mnt/data/world_universities_and_domains.json:ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_WORKERS=1
      - DB_HOST=curriculum-skill-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=skillcrawl
      - API_TRACKER_BASE_URL=https://skillab-tracker.csd.auth.gr/api
      - API_SKILL_EXTRACTOR_BASE_URL=https://portal.skillab-project.eu/esco-skill-extractor #to ask who use it, maybe move to auth
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
  


  # -- to Add more --
  # archetypal & hcv
  # and forecasters
  
  
volumes:
  user_management_postgresql_data:
  curriculum_skills_mysql: